---
name: prerelease

on:
  release:
    types: [prereleased]

env:
  AWS_DEFAULT_REGION: us-east-1
  CURL_CACHE_DIR: ~/.cache/curl
  PIP_CACHE_DIR: ~/.cache/pip
  RUN_TMATE: ${{ secrets.RUN_TMATE }}

jobs:
  diagnostics:
    name: Run diagnostics
    runs-on: ubuntu-latest
    steps:
      # Note that a duplicate of this step must be added at the top of
      # each job.
      - id: harden-runner
        name: Harden the runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - id: github-status
        name: Check GitHub status
        uses: crazy-max/ghaction-github-status@v3
      - id: dump-context
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v2
  prerelease:
    needs:
      - diagnostics
    runs-on: ubuntu-latest
    steps:
      - id: harden-runner
        name: Harden the runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - id: setup-env
        uses: cisagov/setup-env-github-action@develop
      - uses: actions/checkout@v4
      - id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        env:
          BASE_CACHE_KEY: "${{ github.job }}-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-\
            packer${{ steps.setup-env.outputs.packer-version }}-\
            tf-${{ steps.setup-env.outputs.terraform-version }}-"
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
            ${{ env.CURL_CACHE_DIR }}
          key: "${{ env.BASE_CACHE_KEY }}\
            ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ env.BASE_CACHE_KEY }}
      - name: Setup curl cache
        run: mkdir -p ${{ env.CURL_CACHE_DIR }}
      - name: Install Packer
        env:
          PACKER_VERSION: ${{ steps.setup-env.outputs.packer-version }}
        run: |
          PACKER_ZIP="packer_${PACKER_VERSION}_linux_amd64.zip"
          curl --output ${{ env.CURL_CACHE_DIR }}/"${PACKER_ZIP}" \
            --time-cond ${{ env.CURL_CACHE_DIR }}/"${PACKER_ZIP}" \
            --location \
            "https://releases.hashicorp.com/packer/${PACKER_VERSION}/${PACKER_ZIP}"
          sudo unzip -d /opt/packer \
            ${{ env.CURL_CACHE_DIR }}/"${PACKER_ZIP}"
          sudo mv /usr/local/bin/packer /usr/local/bin/packer-default
          sudo ln -s /opt/packer/packer /usr/local/bin/packer
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.setup-env.outputs.terraform-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade \
                      --requirement requirements.txt
      - name: Assume AWS build role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.BUILD_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 14400  # 4 hours
      # When called by Packer, Ansible will find /usr/bin/python3 and
      # use it; therefore, we must ensure that /usr/bin/python3 points
      # to the version of Python that we installed in the
      # actions/setup-python step above.  This can hose other tasks
      # that are expecting to find the system Python at that location,
      # though, so we undo this change after running Packer.
      - name: Create a /usr/bin/python3 symlink to the installed python
        run: |
          sudo mv /usr/bin/python3 /usr/bin/python3-default
          sudo ln -s ${{ env.pythonLocation }}/bin/python3 \
          /usr/bin/python3
      - name: Install process user data file script dependencies
        run: python -m pip install boto3 jinja2
      - name: Process user data file
        id: process-user-data
        # Process the user data script to set the Windows Administrator
        # password to the value retrieved from AWS Parameter Store. Set a step
        # output to use the retrieved password as the winrm_password value
        # with Packer via command line argument.
        run: python .github/scripts/process_user_data_file.py
      - name: Install Packer plugins
        run: packer init src
      - name: Create machine image
        env:
          GITHUB_IS_PRERELEASE: ${{ github.event.release.prerelease }}
          GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_RELEASE_URL: ${{ github.event.release.html_url }}
        run: |
          packer build -timestamp-ui \
            -var is_prerelease=${{ github.event.release.prerelease }} \
            -var release_tag=${{ github.event.release.tag_name }} \
            -var release_url=${{ github.event.release.html_url }} \
            -var winrm_password=${{ steps.process-user-data.outputs.pass }} \
            src/packer.pkr.hcl
      - name: Remove /usr/bin/python3 symlink to the installed python
        run: |
          sudo mv /usr/bin/python3-default /usr/bin/python3
      - name: Setup tmate debug session
        uses: mxschmitt/action-tmate@v3
        if: env.RUN_TMATE
